[tool.poetry]
name = "fixmydata"
version = "0.1.0"
description = "A Python library for data cleaning and preprocessing"
authors = ["Johann Lloyd Megalbio <megalbio.johann@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/DirtCrew53/Fixmydata"
repository = "https://github.com/DirtCrew53/Fixmydata"


# Optional: if you want to include dependencies that are only needed for testing, etc.
[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.3.0"
numpy = "^1.21.0"

# Optional: if you're using dev dependencies
[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
# The build system requires setuptools and wheel
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
